"use client";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Select } from "@/components/ui/select";
import { Slider } from "@/components/ui/slider";
import { Switch } from "@/components/ui/switch";
import type { SourceStatus } from "@/types";
import { useTheme } from "next-themes";
import { useEffect, useState } from "react";

const TOPICS = ["Agentic AI","RAG","MCP","Multimodal","Local LLM","Reasoning Models","AI Safety"];
const DEFAULT_WEIGHTS = { research: 55, novelty: 60, trust: 70, interest: 65, community: 45 };
type Settings = { language: string; view: string; notifications: boolean; interests: string[]; freshnessDays: number; weights: typeof DEFAULT_WEIGHTS };
const DEFAULTS: Settings = { language: "tr", view: "grid", notifications: true, interests: TOPICS.slice(0,5), freshnessDays: 14, weights: DEFAULT_WEIGHTS };
export function SettingsPanel({ version }: { version: string }) {
  const [settings,setSettings] = useState(DEFAULTS); const [sources,setSources] = useState<SourceStatus[]>([]); const [readiness,setReadiness] = useState<Record<string, unknown>>({}); const [saved,setSaved] = useState(false); const { theme,setTheme } = useTheme();
  useEffect(() => { Promise.all([fetch("/api/preferences").then((r) => r.json()),fetch("/api/sources").then((r) => r.json()),fetch("/api/system/readiness").then((r) => r.json())]).then(([preferences,sourcePayload,readyPayload]) => { setSettings({ ...DEFAULTS,...preferences,weights:{ ...DEFAULT_WEIGHTS,...preferences.weights } }); setSources(sourcePayload.data ?? []); setReadiness(readyPayload.data ?? {}); }).catch(() => undefined); }, []);
  function toggleInterest(topic: string) { setSettings((value) => ({ ...value,interests:value.interests.includes(topic) ? value.interests.filter((item) => item !== topic) : [...value.interests,topic] })); }
  async function toggleSource(source: SourceStatus) { const response = await fetch(`/api/sources/${source.id}`, { method: "PATCH", headers: { "content-type":"application/json" }, body: JSON.stringify({ isActive: source.status === "disabled" || source.status === "paused" }) }); const payload = await response.json(); if (response.ok) setSources((value) => value.map((item) => item.id === source.id ? payload.data : item)); }
  async function save() { await fetch("/api/preferences", { method:"PUT",headers:{ "content-type":"application/json" },body:JSON.stringify(settings) }); setSaved(true); window.setTimeout(() => setSaved(false),1800); }
  async function importOpml(file: File) { const form = new FormData(); form.append("file",file); const response = await fetch("/api/import/opml",{ method:"POST",body:form }); const payload = await response.json(); if (response.ok) setSources((value) => [...value,...payload.data]); }
  async function restoreJson(file: File) { const form = new FormData(); form.append("file",file); const response = await fetch("/api/import/json",{ method:"POST",body:form }); if (response.ok) window.location.reload(); }
  const weightLabels: Array<[keyof typeof DEFAULT_WEIGHTS,string]> = [["research","Araştırma önemi"],["novelty","Yenilik"],["trust","Kaynak güvenilirliği"],["interest","Kişisel ilgi"],["community","Topluluk sinyali"]];
  return <div className="space-y-6">
    <Card><CardHeader><CardTitle className="text-base">Local çalışma alanı</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-3"><div className="rounded-xl border p-4"><p className="text-xs text-muted-foreground">Depolama</p><p className="font-medium">SQLite · yalnızca bu cihaz</p></div><div className="rounded-xl border p-4"><p className="text-xs text-muted-foreground">İçerik</p><p className="font-medium">{String(readiness.contentCount ?? 0)} kayıt</p></div><div className="rounded-xl border p-4"><p className="text-xs text-muted-foreground">Scheduler</p><p className="font-medium">{(readiness.scheduler as { healthy?: boolean } | undefined)?.healthy ? "Çalışıyor" : "Bekliyor"}</p></div></CardContent></Card>
    <div className="grid gap-4 xl:grid-cols-2"><Card><CardHeader><CardTitle className="text-base">Görünüm</CardTitle></CardHeader><CardContent className="grid gap-4 md:grid-cols-2"><div className="space-y-2"><Label>Dil</Label><Select value={settings.language} onChange={(e) => setSettings({ ...settings,language:e.target.value })}><option value="tr">Türkçe</option><option value="en">English</option></Select></div><div className="space-y-2"><Label>Varsayılan görünüm</Label><Select value={settings.view} onChange={(e) => setSettings({ ...settings,view:e.target.value })}><option value="grid">Grid</option><option value="list">Liste</option><option value="compact">Kompakt</option></Select></div></CardContent></Card><Card><CardHeader><CardTitle className="text-base">Tema ve bildirim</CardTitle></CardHeader><CardContent className="space-y-3"><label className="flex items-center justify-between rounded-xl border p-3"><span className="text-sm">Koyu tema</span><Switch checked={theme === "dark"} onChange={(e) => setTheme(e.target.checked ? "dark" : "light")} /></label><label className="flex items-center justify-between rounded-xl border p-3"><span className="text-sm">Önemli gelişme bildirimleri</span><Switch checked={settings.notifications} onChange={(e) => setSettings({ ...settings,notifications:e.target.checked })} /></label></CardContent></Card></div>
    <div className="grid gap-4 xl:grid-cols-2"><Card><CardHeader><CardTitle className="text-base">İlgi alanları</CardTitle></CardHeader><CardContent className="flex flex-wrap gap-2">{TOPICS.map((topic) => <Button key={topic} type="button" size="sm" variant={settings.interests.includes(topic) ? "default" : "outline"} onClick={() => toggleInterest(topic)}>{topic}</Button>)}</CardContent></Card><Card><CardHeader><CardTitle className="text-base">Veri kaynakları</CardTitle></CardHeader><CardContent className="space-y-2">{sources.map((source) => <label key={source.id} className="flex items-center justify-between rounded-xl border p-3"><span><span className="block text-sm font-medium">{source.name}</span><span className="text-xs text-muted-foreground">{source.type}</span></span><Switch checked={source.status !== "disabled" && source.status !== "paused"} onChange={() => toggleSource(source)} /></label>)}</CardContent></Card></div>
    <Card><CardHeader><CardTitle className="text-base">Deterministik trend ayarları</CardTitle></CardHeader><CardContent className="space-y-5"><div className="space-y-2"><div className="flex justify-between text-sm"><span>İçerik tazelik penceresi</span><Badge tone="subtle">{settings.freshnessDays} gün</Badge></div><Slider min={3} max={60} step={1} value={settings.freshnessDays} onChange={(e) => setSettings({ ...settings,freshnessDays:Number(e.target.value) })} /></div>{weightLabels.map(([key,label]) => <div key={key} className="space-y-2"><div className="flex justify-between text-sm"><span>{label}</span><Badge tone="subtle">%{settings.weights[key]}</Badge></div><Slider min={0} max={100} step={1} value={settings.weights[key]} onChange={(e) => setSettings({ ...settings,weights:{ ...settings.weights,[key]:Number(e.target.value) } })} /></div>)}</CardContent></Card>
    <Card><CardHeader><CardTitle className="text-base">Yedek ve dışa aktarma</CardTitle></CardHeader><CardContent className="flex flex-wrap items-center gap-2"><Button onClick={() => { window.location.href="/api/export?format=json"; }}>JSON tam yedek</Button><Button variant="outline" onClick={() => { window.location.href="/api/export?format=csv"; }}>CSV içerik</Button><Button variant="outline" onClick={() => { window.location.href="/api/export?format=opml"; }}>OPML kaynaklar</Button><label className="cursor-pointer rounded-xl border border-input px-4 py-2 text-sm font-medium transition hover:bg-accent">OPML içe aktar<input className="sr-only" type="file" accept=".opml,.xml,text/xml" onChange={(event) => { const file=event.target.files?.[0]; if(file) importOpml(file); }} /></label><label className="cursor-pointer rounded-xl border border-input px-4 py-2 text-sm font-medium transition hover:bg-accent">JSON yedeği birleştir<input className="sr-only" type="file" accept=".json,application/json" onChange={(event) => { const file=event.target.files?.[0]; if(file) restoreJson(file); }} /></label></CardContent></Card>
    <div className="flex items-center justify-between"><p className="text-sm text-muted-foreground">Savvy v{version} · AI/LLM yapılandırılabilir</p><div className="flex items-center gap-3">{saved ? <span className="text-sm text-emerald-400">Ayarlar kaydedildi.</span> : null}<Button onClick={save}>Ayarları kaydet</Button></div></div>
  </div>;
}
