"use client";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import type { RepositoryDocument } from "@/types";
import { Github, LoaderCircle, Sparkles, Star } from "lucide-react";
import { useCallback, useEffect, useRef, useState } from "react";

export function GithubDeepDive({ contentId, initialDocument, autoStart = false }: { contentId: string; initialDocument?: RepositoryDocument; autoStart?: boolean }) {
  const [document, setDocument] = useState(initialDocument); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const started = useRef(false);
  const dive = useCallback(async () => { setLoading(true); setError(""); try { const response = await fetch(`/api/research/repos/${encodeURIComponent(contentId)}/deep-dive`, { method: "POST" }); const data = await response.json() as { repositoryDocument?: RepositoryDocument; error?: string }; if (!response.ok || !data.repositoryDocument) throw new Error(data.error ?? "GitHub Deep Dive oluşturulamadı."); setDocument(data.repositoryDocument); } catch (reason) { setError(reason instanceof Error ? reason.message : "GitHub Deep Dive oluşturulamadı."); } finally { setLoading(false); } }, [contentId]);
  useEffect(() => { if (autoStart && !started.current) { started.current = true; void dive(); } }, [autoStart, dive]);
  return <section className="space-y-3"><Card className="border-primary/20 bg-primary/5"><CardHeader className="gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-medium uppercase tracking-[0.16em] text-primary">GitHub Deep Dive</p><CardTitle className="mt-1 text-base">Depo ve ilgili projeler</CardTitle><p className="mt-1 text-sm text-muted-foreground">README yerelde saklanır; konu ve açıklama benzerliğine göre ilgili depolar aranır.</p></div><Button size="sm" onClick={dive} disabled={loading}>{loading ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <Sparkles className="h-4 w-4" />}{document?.status === "ready" ? "Yenile" : "DEEP DIVE"}</Button></CardHeader>{error ? <CardContent className="pt-0 text-sm text-destructive">{error}</CardContent> : null}</Card>{loading ? <p className="flex items-center gap-2 text-sm text-muted-foreground"><LoaderCircle className="h-4 w-4 animate-spin" /> README ve ilgili depolar aranıyor…</p> : null}{document?.status === "ready" ? <div className="space-y-2"><div className="flex flex-wrap gap-2"><Badge tone="success">README hazır</Badge>{document.language ? <Badge tone="subtle">{document.language}</Badge> : null}{document.stars !== undefined ? <Badge tone="subtle"><Star className="mr-1 h-3 w-3" />{document.stars.toLocaleString("tr-TR")}</Badge> : null}</div>{document.relatedRepositories?.map((repo) => <Card key={repo.fullName}><CardContent className="p-3"><a href={repo.url} target="_blank" rel="noreferrer" className="font-medium text-primary hover:underline"><Github className="mr-1 inline h-3.5 w-3.5" />{repo.fullName}</a><p className="mt-1 text-sm text-muted-foreground">{repo.description ?? "Açıklama yok."}</p><p className="mt-1 text-xs text-muted-foreground">{repo.reason}</p></CardContent></Card>)}</div> : null}</section>;
}
